### ISSUE TITLE
Dataset simulation

### ISSUE THREAD

**Issue by jlipovac** [jsgounot/floria_analysis_workflow#1]
Hi,

thank you for the interesting Floria tool. 
I like how you designed the simulation of the 109 Singapore gut metagenome samples dataset. Is it possible to use the pipelines available here to achieve exactly that simulation? If so, could you please provide me an example of the config file that I should use? 

Thanks! :)

**Comment by jsgounot** [comment]
Hi Jkipovac, we used the real reads from this cohort, it wasn't simulated. :)

**Comment by jlipovac** [comment]
Oh, I see. Sorry, I misinterpreted your explanation in the paper. 
Is that dataset publicly available?

**Comment by jsgounot** [comment]
Yes, it is available on [ENA](https://www.nature.com/articles/s41467-022-33782-z#data-availability).

**Comment by jlipovac** [comment]
Thank you! :)
