### ISSUE TITLE
mismatched config keys between descriptions and scipts

### ISSUE THREAD

**Issue by vtnphan** [jsgounot/floria_analysis_workflow#2]
Hello @jsgounot and @bluenote-1577,  I am trying to running the pipeline with some example data from Illumina, the  I found a problem while writing my own config file for production pipeline. Below is details and my attempt to fix that.

Keys described in config_desc.md
https://github.com/jsgounot/floria_analysis_workflow/blob/440d4060211d35ef77772458f347f02cc4276ba5/config_desc.md?plain=1#L58-L72 

Follow this line from multiple_species_production.snk file:
https://github.com/jsgounot/floria_analysis_workflow/blob/440d4060211d35ef77772458f347f02cc4276ba5/multiple_species_production.snk#L49 

The config file should be:
```json
"samples": {
        "sample_name": {
            "illumina": {
                "R1": "path/to/read_1.fastq.gz",
                "R2": "path/to/read_1.fastq.gz"
            }
            
        }
    }
```

**Comment by jsgounot** [comment]
Hi @laclac102,

thanks for the comment. A few things:
* The section in the readme you quoted is for the assessment pipeline, not the production one you seem to use (`multiple_species_production.snk`).
* There is still a mistake there as you pointed out, thanks for letting me know, I'll fix it asap.

Let me know if there are additional issues.
JS

**Comment by jsgounot** [comment]
Hi @laclac102, I've pushed a fix that should normalize the way to input Illumina for all pipelines. Illumina reads must be specified the way it is indicated in the manual now (`illumina_r1` and `illumina_r2`). I also had to fix a couple of issues that I didn't catch before.

**Comment by vtnphan** [comment]
@jsgounot great! Thank you.

**Comment by vtnphan** [comment]
And can I ask about the average time for running production workflow? As I am running that workflow with UHGG database you mentioned in README, but it was the 4th day since it is executed. The worklow now is on its flsp_link_ploidy_prod and flsp_link_assembly_prod one. Eventhough I was use --cores 32.

**Comment by jsgounot** [comment]
Hard to answer this question without knowing the number of samples, depth, what you asked in your configuration file, and the current state of the pipeline. You're probably stuck into another step though, as the [two rules](https://github.com/jsgounot/floria_analysis_workflow/blob/8b70769d33e1fafa2efe63329db6ec16814954e4/workflow/floria_presplit.snk#L174) you mentioned before are just making symbolic links.

**Comment by jsgounot** [comment]
I'll close this issue. Feel free to reopen the issue if you have an error related to the last commit and linked to your original issue. Otherwise, open a new one. Feel free to open a new one if your pipeline is still stuck and would like to know more, but I'd need your current pipeline log and configuration file to answer.
